### ISSUE TITLE
where can I get dmzap tools?

### ISSUE THREAD

**Issue by cyu1998** [westerndigitalcorporation/dm-zap#2]

**Comment by yhr** [comment]
@cyu1998 : As far as i know, you don't the tool - the metadata is initilized when the device mapper is setup(it is not persisted yet). Just skip the tool step.

**Comment by cyu1998** [comment]
> @cyu1998 : As far as i know, you don't the tool - the metadata is initilized when the device mapper is setup(it is not persisted yet). Just skip the tool step.

thank you for answering
but when i use the command "echo "0 `blockdev --getsize ${dev}` zap ${dev}" | dmsetup create dmzap-`basename ${dev}`",it returns "device-mapper: reload ioctl on dmzap-nvme0n1 (253:1) failed:Invalid argument"
my environment is qemu and my zns device is emulated by qemu
do you have any idea about it? thank you

**Comment by yhr** [comment]
@MaisenbacherD : Could you point @cyu1998 to the right parameters for setting up dm-zap? It looks like the readme needs to be patched as well

**Comment by MaisenbacherD** [comment]
Updated the README.md with an updated `Usage` section (https://github.com/westerndigitalcorporation/dm-zap/pull/3).

@cyu1998 could you see if that works out for you? :)

**Comment by cyu1998** [comment]
> 

thank you for the update, it is working now!

**Comment by cyu1998** [comment]
> Updated the README.md with an updated `Usage` section (#3).
> 
> @cyu1998 could you see if that works out for you? :)

thank you for your update , it is working now!
